# Generated by Django 4.2.5 on 2023-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthYear',
            field=models.CharField(default='', max_length=10),
        ),
    ]
